type Post {
  id: ID!
  title: String!
  user: User!
  views: Int!
  comments: [Comment]
}

type User {
  id: ID!
  name: String!
}

type Comment {
  id: ID!
  user: User!
  body: String!
  date: String!
}
